# Generated by Django 4.1.7 on 2023-03-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0002_decision_user_option'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='decision',
            name='is_daily_decision',
            field=models.BooleanField(default=False),
        ),
    ]
