# Generated by Django 4.1.7 on 2023-04-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0004_auto_20230411_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='color1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imageset',
            name='color2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='image',
            field=models.ImageField(default='default_image.jpg', null=True, upload_to='image_sets/'),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
