# Generated by Django 4.1.7 on 2023-04-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0006_alter_imageset_color1_alter_imageset_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='randomizer.imageset'),
        ),
    ]
