# Generated by Django 4.1.7 on 2023-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0007_decision_image_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='color1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imageset',
            name='color2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
