# Generated by Django 4.1.7 on 2023-05-20 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0012_remove_situation_decision_decision_situation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='situation',
        ),
        migrations.AddField(
            model_name='situation',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situations', to='randomizer.decision'),
        ),
    ]
