# Generated by Django 4.1.7 on 2023-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0013_remove_decision_situation_situation_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='situation',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Situation',
        ),
    ]
