# Generated by Django 4.1.7 on 2023-05-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0016_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
