# Generated by Django 4.1.7 on 2023-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0017_alter_decision_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='is_public_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decision',
            name='is_quick_decision',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decision',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
