# Generated by Django 4.1.7 on 2023-05-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomizer', '0018_decision_is_public_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='image_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='randomizer.imageset'),
        ),
    ]
